#!/bin/bash
VERSION=3.6.2
RUN="TeamSpeak3-Client-linux_amd64-3.6.2.run"
cd /tmp
wget https://files.teamspeak-services.com/releases/client/$VERSION/TeamSpeak3-Client-linux_amd64-$VERSION.run
bash $RUN
mv TeamSpeak3-Client-linux_amd64 /opt/
rm -f $RUN
