#!/bin/bash
VERSION=3.5.3
RUN="TeamSpeak3-Client-linux_x86-$VERSION.run"
cd /tmp
wget https://files.teamspeak-services.com/releases/client/$VERSION/TeamSpeak3-Client-linux_amd64-$VERSION.run
bash $RUN
mv TeamSpeak3-Client-linux_amd64 /opt/
rm -f $RUN
